version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo 
      ME_CONFIG_MONGODB_PORT: 27017

      ME_CONFIG_BASICAUTH_USERNAME: orgpulse
      ME_CONFIG_BASICAUTH_PASSWORD: cliorg
    depends_on:
      - mongo 

volumes:
  mongo-data: