version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Optional Redis service
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  mongo-data: